# Optional as there are CLI arguments too, defaults to the current working directory
# repo_path = "/home/simeonzahariev/work/Manta"

# Mandatory 
version_pattern = "v[0-9]+.[0-9]+.[0-9]+"

[labels]
L-added = "Added"
L-changed = "Changed"
L-deprecated = "Deprecated"
L-removed = "Removed"
L-fixed = "Fixed"
L-security = "Security"

[suffix_labels]
A-manta = "MA"
A-calamari = "CA"

[prefix_labels]

